const slpMode = {
	COMPREHENSIVE: 'comprehensive',
	FAST: 'fast',
};

const slpParams = {
	API_KEY: 'ApiKey',
	TAG_HASH: 'TagHash',
	EVENT_TYPE: 'EventType',
	CHANNEL: 'Channel',
	JA3: 'JA3',
	REMOTE_ADDRESS: 'RemoteAddr',
	X_REAL_IP: 'XRealIP',
	TRUE_CLIENT_IP: 'TrueClientIP',
	CONTENT_TYPE: 'ContentType',
	CACHE_CONTROL: 'CacheControl',
	PRAGMA: 'Pragma',
	CONNECTION: 'Connection',
	X_REQUESTED_WITH: 'XRequestedWith',
	ORIGIN: 'Origin',
	ACCEPT_CHARSET: 'AcceptCharset',
	ACCEPT_LANGUAGE: 'AcceptLanguage',
	ACCEPT_ENCODING: 'AcceptEncoding',
	ACCEPT: 'Accept',
	REFERER: 'Referer',
	X_FORWARDED_FOR: 'XForwardedFor',
	USER_AGENT: 'UserAgent',
	HOST: 'Host',
	HEADER_NAMES: 'HeaderNames',
	CLIENT_IP: 'ClientIP',
	REQUEST_URL: 'RequestURL',
	REQUEST_TIME: 'RequestTime',
	METHOD: 'Method',
	RESOURCE_TYPE: 'ResourceType',
	FORWARDED: 'Forwarded',
	MIDDLEWARE_VERSION: 'MiddlewareVersion',
	REQUEST_ID: 'RequestId',
	EMAIL: 'Email',
	PHONE: 'Phone',
	TAG_ID: 'TagId',
	MODE: 'Mode',
};

module.exports = {
	slpMode,
	slpParams,
};
